using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HotelAPI.Models
{
    public class Booking
    {
        // Unique identifier for the booking, auto-generated by the database
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        // Foreign key for the room associated with the booking
        [Required]
        public int RoomId { get; set; }

        // Navigation property to the Room entity
        [ForeignKey("RoomId")]
        public virtual Room Room { get; set; }

        // Foreign key for the guest associated with the booking
        [Required]
        public int GuestId { get; set; }

        // Navigation property to the Guest entity
        [ForeignKey("GuestId")]
        public virtual Guest Guest { get; set; }

        // Foreign key for the employee who managed the booking
        [Required]
        public int EmployeeId { get; set; }

        // Navigation property to the Employee entity
        [ForeignKey("EmployeeId")]
        public virtual Employee Employee { get; set; }

        // The start date of the booking
        [Required]
        public DateTime StartDate { get; set; }

        // The end date of the booking
        [Required]
        public DateTime EndDate { get; set; }

        // The total cost of the booking, must be a non-negative decimal
        [Required]
        [Range(0, double.MaxValue)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal TotalCost { get; set; }
    }
}
