using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HotelAPI.Models
{
    public class RoomType
    {
        // Unique identifier for the room type, auto-generated by the database
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        // Name of the room type, required and limited to 50 characters
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        // Description of the room type, optional and limited to 255 characters
        [StringLength(255)]
        public string Description { get; set; }

        // Navigation property for related Rooms, allowing access to all rooms of this type
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
