using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HotelAPI.Models
{
    public class Room
    {
        // Unique identifier for the room, auto-generated by the database
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        // Room number, required and limited to 10 characters
        [Required]
        [StringLength(10)]
        public string RoomNumber { get; set; }

        // Foreign key for the room type, required
        [Required]
        public int RoomTypeId { get; set; }

        // Navigation property for the associated RoomType entity
        [ForeignKey("RoomTypeId")]
        public virtual RoomType RoomType { get; set; }

        // Price per night for the room, required, must be a non-negative value, and stored as decimal with two decimal places
        [Required]
        [Range(0, double.MaxValue)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal PricePerNight { get; set; }

        // Availability status of the room, indicating if it is available for booking
        public bool Availability { get; set; }

        // Maximum number of persons allowed in the room, must be at least 1
        [Range(1, int.MaxValue)]
        public int MaxOccupancyPersons { get; set; }

        // Navigation property for related bookings, allowing access to all bookings for this room
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
